# Generated by Django 5.1.4 on 2025-03-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
