# Generated by Django 5.1.4 on 2025-03-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
