# Generated by Django 5.1.4 on 2025-03-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_alter_vendor_address_alter_vendor_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel', models.CharField(max_length=100)),
                ('inclusive', models.CharField(max_length=100)),
                ('flight', models.CharField(max_length=100)),
                ('guide', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='packages/')),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Packages',
        ),
    ]
