# Generated by Django 5.1.4 on 2025-03-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_package_delete_packages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='package',
            name='inclusive',
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
